README.md

Refactory is also full remote, so here's my PR to add it. Thank you!

Add Refactory

---

src/data.json

Spreaker is a full remote company founded in Italy in 2010, running a full-remote international team since 2015. We are  in the podcasting industry providing an hosting, distribution and monetization platform for content creators.

Add Spreaker

---

src/data.json

Ho aggiornato lo stack Prima per includere anche altri tool/linguaggi.

updated prima stack

---

src/data.json

I'm adding iSolutions as a remote-friendly company that targets Italian talents

Adding iSolutions to data.json

---

CONTRIBUTING.md

as titled.
I was confused about the case of the file name

chore: add info about file name case

---

data/cloud_software/nearform.json

[@nearform](https://github.com/nearform) is a remote-first company since 2012 and brings people together in highly-skilled teams spread out across 27 countries that collectively build digital solutions for global challenges.
It hires employers and contractors too.

Add NearForm

---

data/cloud_software/superlayer.json
data/design_ux/superlayer.json

Superlayer is a young and ambitious company, born and distributed across Europe. Today we have members in Italy, France and the UK.
We’re building a smart co-pilot for sales teams and sit at the intersection of data science and sales. We provide the tools to track, monitor and fix sales execution through a system of rules and alerts. This saves time for both sales ops and sales, while increasing their performance in a market worth many $B.

Add Superlayer

---

data/cloud_software/boom.json

Changed NextJS to NestJS in BOOM tech stack

Fixed BOOM tech stack

---

data/cloud_software/zappyrent.json

@zappyrent is a medium and long-term rental platform which handles the entire process of rental: from listing to the management of contracts, from security deposits to monthly rent payments.
Our tech team works remotely since Sept. 2020
It hires employers and contractors too.

Added Zappyrent

---

data/cloud_software/subito.json
data/design_ux/subito.json

Subito is a remote-friendly company that frequently hires Dev and UX designers

Add Subito

---

data/cloud_software/overit.json

chore(companies): added overit

Added OverIT

---

data/cloud_software/register_s.p.a.json

Adding Register SpA to the company list.

Add Register SpA

---

data/cloud_software/jimdo.json

Added Jimdo as a company hiring remotely.

Add jimdo to the list of product companies doing SaaS

---

data/cloud_software/gorgias.json

Adds Gorgias to the list of companies. The team is growing fast and made of top class people, product and the company are doing great, and the founders are actually nice and smart people. Come join us!

Adds Gorgias

---

data/cloud_software/dove_it.json

It should add Dove.it as a remote-first software company.

Added Dove.it to remote software company list

---

data/cloud_software/vlk_studio.json

```JSON
{
"name": "VLK Studio",
"career_page_url": "https://www.linkedin.com/company/vlk-studio",
"url": "https://vlkstudio.com/",
"type": "Consulting",
"tags": [
"JavaScript",
"TypeScript",
"React",
"React Native",
"Node.js",
"Open source",
"Full remote",
".NET",
"morfeojs",
"nocode"
]
}
```

Add VLK Studio

---

data/cloud_software/garden.json

improvement: add garden.io to the list of companies

---

CONTRIBUTING.md
data/cloud_software/immobiliare.it.json
data/design_ux/immobiliare.it.json

[feat/immobiliare-labs afa0894] feat: add the correct info to immobiliare.it and add more tags.
Thanks

feat: add the correct info to immobiliare.it and add more tags

---

data/cloud_software/casavo.json

This should add casavo to the tech company list.

Add Casavo

---

data/cloud_software/sysdig.json

Adding technologies to the Sysdig JSON file.

Improving sysdig tech stack

---

data/cloud_software/belka.json
data/cloud_software/casavo.json
data/cloud_software/docebo.json
data/cloud_software/facile.it.json
data/cloud_software/flowing.json
data/cloud_software/innoteam.json
data/cloud_software/lastminute.com.json
data/cloud_software/microsoft.json
data/cloud_software/overit.json
data/cloud_software/prima.json
data/cloud_software/redhat.json
data/cloud_software/subito.json
data/cloud_software/vmware.json
data/cloud_software/zendesk.json
data/design_ux/zendesk.json
data/marketing_writing/zendesk.json

Refactored remote policies for all the companies I know or I talked to.

Remote policies

---

data/cloud_software/vlk_studio.json

It adds the remote and the hiring policy to the VLK Studio JSON.

Add VLK Studio remote and hiring policy

---

data/cloud_software/duckduckgo.json
data/cloud_software/subito.json
data/cloud_software/sysdig.json
data/design_ux/duckduckgo.json
data/design_ux/sysdig.json
data/hr/duckduckgo.json
data/marketing_writing/duckduckgo.json

* Adding DuckDuckGo
* Other Companies improvements

DuckDuckGo + Fixes

---

data/cloud_software/sparkfabrik.json

Added our company. Should be all good, let me know if you spot any errors.

Added SparkFabrik - Remote cloud-native software development company

---

data/cloud_software/faceit.json

Added faceit

---

data/cloud_software/immobiliare.it.json
data/design_ux/immobiliare.it.json

[fix/improve-immobiliare-policy 266f265] fix: improve immobiliare policy

fix: improve immobiliare policy

---

data/cloud_software/pagopa.json

Add PagoPA to the list of companies

add pagopa.json

---

data/cloud_software/macai.json

feat(alessandro): added Macai

---

data/cloud_software/young_platform.json

Add Youngplatform

---

data/cloud_software/radical_storage.json

added radical storage

---

data/cloud_software/esteco.json

- Small fix to company name ("SpA" is not needed)
- Added remote work policy. At the moment we allow everybody to work remotely 5 days a week
- Added hiring policy.

Updated company hiring and remote work policies

---

data/cloud_software/bitbull.json

Hello! We (BitBull) would like to be part of the list :)
Regards
Gennaro

Add BitBull data

---

data/cloud_software/ignite.json

Add Ignite (formerly known as Tendermint).

add Ignite (ignt.com)

---

README.md
data/cloud_software/collabora.json

Add the company I've been working with fully-remotely for 10 years. :)

Add Collabora Ltd.

---

data/cloud_software/cloud_academy.json
data/design_ux/cloud_academy.json

- Update Cloud Academy Remote Policy
- Add Cloud Academy in Design category

Update Cloud Academy

---

data/cloud_software/nearform.json

setting the value for the new columns added in #76

fix: new columns' value

---

data/cloud_software/treatwell.json

Adds [TreatWell](https://treatwell.com/openings/) to the list

feat: add treatwell.json

---

data/lastminute.com.json

update lastminute.com tags

---

data/capbase.json
data/elastic.json
data/hasura.json
data/miinto.json
data/remote.json
data/searchmetrics.json
data/wave.json
data/workwave.json

I added some companies I recently got interviewed from.
Thanks for the amazing project ❤️

Add and update some companies

---

data/exein.json

Hi there! This PR is to add Exein.io to the list of awesome italia remote companies.

feat: add exein.io

---

data/devinterface.json

Thank you for the great work you are doing

Please add DevInterface to the list

---

data/txt
data/txt.json

Added TXT Group company profile

Add TXT Group

---

data/heply.json
data/human-analytica.json

Hi, can you please add these two companies? Thank you!

Add Heply and Human Analytica companies

---

data/thoughtworks.json

Adding Thoughtworks Italy to the repo 😄

Add Thoughtworks Italy

---

data/userbot.json

Hello everyone!
I took the liberty of adding a company where I have worked and know well.
I hope I did everything right 😅

add userbot.json

---

data/sighup.json

Add [SIGHUP S.r.l.](https://sighup.io) to the list of remote companies.

add SIGHUP S.r.l.

---

data/remotamente.json

Add remotamente srl

---

data/yoox_netaporter_group.json

This PR adds the YOOX NET-A-PORTER GROUP company

Add YOOX NET-A-PORTER GROUP

---

data/shopify.json

Adding Shopify

---

data/getir.json

Adding getir as remote company, at least for software engineering roles.

Adding getir.com

---

data/cubbit.json

Adding Cubbit

---

data/infovista.json

Adding Infovista

---

data/rome.json

Add Rome Tools

---

data/gitlab.json

Gitlab is now hiring people in Italy. See https://about.gitlab.com/handbook/people-group/employment-solutions/#country-hiring-guidelines

Adding gitlab

---

data/develer.json

Hi, thanks for doing this.
I'm adding my company: https://www.develer.com/

Add Develer

---

data/brave.json
data/wikimedia-foundation.json
data/zapier.json

As per title
* [Brave](https://brave.com)
* [Wikimedia Foundation](https://wikimediafoundation.org/)
* [Zapier](https://zapier.com)

Adding 3 new companies

---

data/alpian.json

Added Alpian

---

data/thefork.json

This add [TheFork](https://www.thefork.com/) in the company list.

Add The Fork

---

data/heritage_holdings.json

This PR adds [Heritage Holdings](https://careers.heritageholdings.co/) as a company full remote friendly

Add Heritage Holdings

---

data/brandbastion.json
data/deel.json
data/doist.json
data/juni.json
data/pexels.json
data/pleo.json
data/primer.json
data/unobravo.json

Here's a list of companies that hire for full-remote roles in Italy. some of them may also hire for non-engineering roles.

Add more companies

---

data/aicof.json

Data file for AICOF s.r.l.  https://www.aicof.it
We are a Software House and System Integrator based in Cagliari - Sardinia - Italy

New company: AICOF s.r.l.

---

README.md
data/agile_lab.json

Added some missing information for Agile Lab (the company I work for) :)

Update AgileLab row

---

data/eco-mind.json

Eco-Mind is a software factory skilled in the design and development of business cloud native, web and mobile solutions, and augmented and virtual reality software. Now is available on _awesome-italia-remote_!

Add Eco-Mind

---

data/amazon.json
data/meta.json
data/microsoft.json
data/redhat.json

Updated info about some big tech companies

Update some companies

---

README.md
data/moneyfarm.json
outputs.json

edit Moneyfarm tags

---

data/dvisionlab.json

Added D/Vision Lab, a remote-first company doing data visualization and cloud software.

Added D/Vision Lab

---

data/nebulab.json

As per title, adding nebulab company.

feat: add nebulab.json

---

data/xriba.json

As per title, add Xriba company.

feat: add xriba.json

---

data/sidea_group.json

As per title, add Sidea Group company.

feat: add sidea_group.json

---

data/fatture_in_cloud.json

As per title, add Fatture in Cloud company.

feat: add fatture_in_cloud.json

---

data/doubleloop.json

Hi, I'd like to add `doubleloop` company to the list. Thank you!

Add doubleloop company

---

data/codermine.json

As per title, add Codermine company.

feat: add codermine.json

---

data/fluentify.json

As per title, add Fluentify company.

feat: add Fluentify company

---

data/intent.json

As per title added Intent company

Added intent

---

data/bitrock.json

As per title, add new company Bitrock.

feat: add new company Bitrock

---

data/meritocracy.json

As per title, add Meritocracy company.

feat: add new company Meritocracy

---

data/storyteq.json

As per title, add new amazing company storyteq!

feat: add new company storyteq

---

data/veed.json

Full remote video editing software company

Add Veed.io

---

data/hopper.json

Added Hopper, a Canadian travel company.

Add Hopper

---

data/shippypro.json

This PR updates the data for the ShippyPro company!

Update ShippyPro data

---

data/namastudio.json

Hi, I'd like to add `Nama Studio` to the list.
Thank you!

Add Nama Studio company

---

data/nearform.json

NearForm has opened an Italian Entity to ease the hiring here in our country 🇮🇹

fix: NearForm hires directly

---

data/hakuna.json

Full remote, distributed company based in Germany.

Add Hakuna

---

data/etiqa.json

chore: etiqa srl new entry 🚀

---

data/tundr.json

Add Tundr company

---

data/bip.json

Add BIP company to the list of remote friendly companies.
Cheers!

Add BIP company

---

data/prontopro.json

```JSON
{
"name": "ProntoPro",
"url": "https://www.prontopro.it/",
"career_page_url": "https://www.prontopro.it/people/careers",
"type": "Product",
"categories": [
"cloud_software"
],
"remote_policy": "-",
"hiring_policies": [
"Direct"
],
"tags": [
"PHP",
"Go",
"AWS",
"Terraform",
"Kubernetes"
]
}
```

Update ProntoPro Career Page

---

data/cardo_ai.json

Adding Cardo AI, a Fintech company based in Milan, Italy.

Add Cardo AI

---

data/cardo_ai.json

Updated Cardo AI's remote policy, since the company has physical offices, but allows the employees to choose freely where will they work from.

Update Cardo AI

---

data/gipo.json

Added Gipo to the list (aka Ianiri Informatica), an Italian company developing software for the healthcare (part of Docplanner group)

added gipo - ianiri informatica

---

data/bmeme.json

Added Bmeme, a digital factory based in Rome.

Added Bmeme

---

data/exibe.json

Exibe offers IT consultancy services to companies to guide their businesses in the process of Digital Transformation by providing support to them with software, app, IoT and cloud-based solutions.
https://www.exibe.it/

Adding Exibe

---

data/geodatalab.json

Added GeoDataLab

---

data/wegg.json

Adding wegg company to the list

Add wegg.json

---

data/the.json

Hi,
I'm currently working in THE I, which has been featured in the CyberSecurity section. Actually the company also works in Software Development and Cloud/DevOps so I added it also in the "Software and Cloud" section.
Moreover, I added our current stack, which has not been specified.
Thank you for adding us in your repository.

Update THE I Technology stack and position

---

data/conio.json

I'm Frontend Developer at Conio Srl.
We have dedicated career page for jobs.

fix career page for Conio Srl

---

data/mostrum.json

add mostrum srl

---

data/cleafy.json

Cleafy helps banks and payment providers deliver the smoothest and safest online experience to their customers. 
They hire hybrid or full remote

adding cleafy

---

data/bizaway.json

Add [BizAway](https://bizaway.com).

Add BizAway

---

data/bhlack.json
data/cardo_ai.json
data/devmy.json
data/dscovr.json
data/edb.json
data/engage_it_services.json
data/engage_labs.json
data/fitprime.json
data/innovyou.json
data/jagaad.json
data/par-tec.json
data/sorintLab.json
data/sorintOSS.json
data/toduba.json
data/vlk_studio.json

Aligns the spelling of a few tags across the data files.
- Next.js
- PostgreSQL
- Open Source
- REST API
The PR will cause a merge conflict with #414 due to the spelling of 3 file names, which can be easily resolved, though.
- `data/Bhlack.json`
- `data/sorintLab.json`
- `data/sorintOSS.json`

Align spelling of some tags
